[project]
name = 'Panspermia-Tracking-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.evolutionary-divergence]
path = 'contracts/evolutionary-divergence.clar'
clarity_version = 2
epoch = 2.5

[contracts.planetary-colonization]
path = 'contracts/planetary-colonization.clar'
clarity_version = 2
epoch = 2.5

[contracts.seed-distribution]
path = 'contracts/seed-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
